### POst signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"email": "test1@test.com",
"password": "12345"
}


### POST signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
"email": "test@test.com",
"password": "12345"
}

###
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout



### Get a particular user
GET http://localhost:3000/auth/1

### Get all users
GET http://localhost:3000/auth

### Delete a user by id
DELETE http://localhost:3000/auth/6

### Update a user
PATCH  http://localhost:3000/auth/65546
Content-Type: application/json

{
"email": "newEmail3@hello.de"
}


